# Generated by Django 4.1.7 on 2023-04-22 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule_bus', models.CharField(max_length=12)),
                ('nb_place', models.PositiveSmallIntegerField(default=0)),
                ('compagnie_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.compagnie')),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_user', models.CharField(max_length=30)),
                ('prenom_user', models.CharField(max_length=50)),
                ('email_user', models.CharField(max_length=60)),
                ('id_user', models.CharField(max_length=10)),
                ('pw_user', models.CharField(max_length=12)),
                ('compagnie_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.compagnie')),
                ('grade_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.grade')),
            ],
        ),
        migrations.CreateModel(
            name='Ligne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville_arr', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='arrivee', to='dashboard.ville')),
                ('ville_dep', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='depart', to='dashboard.ville')),
            ],
        ),
        migrations.CreateModel(
            name='InfoLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_dep', models.DateTimeField()),
                ('prix', models.FloatField(default=0)),
                ('bus_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='companyman.bus')),
                ('ligne_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='companyman.ligne')),
            ],
        ),
    ]
