# Generated by Django 4.1.7 on 2023-05-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyman', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoligne',
            name='place_restante',
            field=models.PositiveSmallIntegerField(default=60),
        ),
    ]
