# Generated by Django 4.1.7 on 2023-05-12 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companyman', '0002_infoligne_place_restante'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateur',
            old_name='id_user',
            new_name='nom_utilisateur',
        ),
    ]
