# Generated by Django 4.1.7 on 2023-05-12 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companyman', '0004_ligne_libelle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ligne',
            name='libelle',
        ),
    ]
