# Generated by Django 4.1.7 on 2023-05-12 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('companyman', '0006_ligne_libelle'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoligne',
            name='compagnie_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.compagnie'),
        ),
    ]
