# Generated by Django 4.2.1 on 2023-05-25 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('companyman', '0008_remove_infoligne_compagnie_id_ligne_duree_trajet'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoligne',
            name='position',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.ville'),
        ),
    ]
