# Generated by Django 4.2.1 on 2023-05-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyman', '0009_infoligne_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoligne',
            name='date_arr',
            field=models.DateTimeField(null=True),
        ),
    ]
