# Generated by Django 4.2.1 on 2023-06-03 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('companyman', '0011_utilisateur_personnel_actif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='compagnie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.compagnie'),
        ),
        migrations.RemoveField(
            model_name='infoligne',
            name='bus_id',
        ),
        migrations.AlterField(
            model_name='infoligne',
            name='ligne_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyman.ligne'),
        ),
        migrations.AlterField(
            model_name='infoligne',
            name='position',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.ville'),
        ),
        migrations.AlterField(
            model_name='ligne',
            name='ville_arr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivee', to='dashboard.ville'),
        ),
        migrations.AlterField(
            model_name='ligne',
            name='ville_dep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depart', to='dashboard.ville'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='compagnie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.compagnie'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='grade_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.grade'),
        ),
        migrations.AddField(
            model_name='infoligne',
            name='bus_id',
            field=models.ManyToManyField(to='companyman.bus'),
        ),
    ]
