# Generated by Django 4.2.1 on 2023-06-03 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('companyman', '0012_alter_bus_compagnie_id_remove_infoligne_bus_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infoligne',
            name='bus_id',
        ),
        migrations.AlterField(
            model_name='infoligne',
            name='ligne_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='companyman.ligne'),
        ),
        migrations.AlterField(
            model_name='infoligne',
            name='position',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.ville'),
        ),
        migrations.AddField(
            model_name='infoligne',
            name='bus_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='companyman.bus'),
        ),
    ]
