# Generated by Django 4.2.1 on 2023-06-05 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companyman', '0014_etat'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='etat_bus',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='companyman.etat'),
        ),
        migrations.AddField(
            model_name='infoligne',
            name='etat_infoligne',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='companyman.etat'),
        ),
    ]
