# Generated by Django 4.1.7 on 2023-04-22 19:42

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companyman', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=20)),
                ('message', models.TextField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Billet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_clt', models.CharField(max_length=30)),
                ('prenom_clt', models.CharField(max_length=50)),
                ('email_clt', models.CharField(max_length=60)),
                ('telephone_clt', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='TG')),
                ('code_billet', models.CharField(max_length=12)),
                ('place', models.SmallIntegerField(default=0)),
                ('montant_billet', models.FloatField()),
                ('infoligne_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='companyman.infoligne')),
            ],
        ),
    ]
