# Generated by Django 4.1.7 on 2023-04-25 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companyman', '0001_initial'),
        ('client', '0002_billet_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='billet',
            name='date_heure',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='billet',
            name='infoligne_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='companyman.infoligne'),
        ),
        migrations.AlterField(
            model_name='billet',
            name='montant_billet',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='billet',
            name='place',
            field=models.SmallIntegerField(default=1),
        ),
    ]
