# Generated by Django 4.1.7 on 2023-04-28 10:06

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('companyman', '0001_initial'),
        ('client', '0004_alter_billet_date_heure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billet',
            name='infoligne_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='companyman.infoligne'),
        ),
        migrations.AlterField(
            model_name='billet',
            name='montant_billet',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='billet',
            name='place',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='billet',
            name='prix',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='billet',
            name='telephone_clt',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='TG'),
        ),
    ]
