# Generated by Django 4.1.7 on 2023-04-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_alter_billet_id_alter_billet_telephone_clt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billet',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
