# Generated by Django 4.1.7 on 2023-05-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_alter_billet_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtatBillet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=20)),
            ],
        ),
    ]
