# Generated by Django 4.1.7 on 2023-05-05 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_billet_etat_billet'),
    ]

    operations = [
        migrations.AddField(
            model_name='billet',
            name='bl_valide',
            field=models.BooleanField(default=True),
        ),
    ]
