# Generated by Django 4.1.7 on 2023-05-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_suggestion_destinataire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billet',
            name='email_clt',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
