# Generated by Django 4.1.7 on 2023-05-24 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_alter_billet_email_clt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billet',
            name='etat_billet',
        ),
        migrations.RemoveField(
            model_name='billet',
            name='infoligne_id',
        ),
        migrations.DeleteModel(
            name='Suggestion',
        ),
        migrations.DeleteModel(
            name='Billet',
        ),
        migrations.DeleteModel(
            name='EtatBillet',
        ),
    ]
