# Generated by Django 4.2.1 on 2023-05-25 14:28

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companyman', '0009_infoligne_position'),
        ('client', '0013_remove_billet_etat_billet_remove_billet_infoligne_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtatBillet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=20)),
                ('destinataire', models.CharField(default='Plateforme', max_length=30)),
                ('message', models.TextField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Billet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_clt', models.CharField(max_length=30)),
                ('prenom_clt', models.CharField(max_length=50)),
                ('email_clt', models.CharField(blank=True, max_length=60, null=True)),
                ('telephone_clt', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='TG')),
                ('code_billet', models.CharField(max_length=12)),
                ('prix', models.FloatField()),
                ('place', models.SmallIntegerField()),
                ('montant_billet', models.FloatField()),
                ('date_heure', models.DateTimeField(auto_now_add=True)),
                ('bl_valide', models.BooleanField(default=True)),
                ('etat_billet', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='client.etatbillet')),
                ('infoligne_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='companyman.infoligne')),
            ],
        ),
    ]
