# Generated by Django 4.2.1 on 2023-06-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0015_billet_carte_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='billet',
            name='moyen_paiement',
            field=models.CharField(default='Stripe', max_length=20),
        ),
    ]
