# Generated by Django 4.2.1 on 2023-06-09 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0016_billet_moyen_paiement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billet',
            name='carte_paiement',
        ),
        migrations.RemoveField(
            model_name='billet',
            name='moyen_paiement',
        ),
    ]
