# Generated by Django 4.2.1 on 2023-06-09 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0017_remove_billet_carte_paiement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billet',
            name='id_paiement',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
